-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Multiply is
port (
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (7 downto 0);
    y : IN STD_LOGIC_VECTOR (4 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of Multiply is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_40_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_cast_fu_44_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_fu_72_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i_cast_cast_fu_80_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_51_fu_66_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_50_fu_58_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_assign_fu_88_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_85_cast_fu_94_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_55_fu_122_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i4_cast_cast_fu_130_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_54_fu_116_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_53_fu_108_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_assign_1_fu_138_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_89_cast_fu_144_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_58_fu_172_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_i9_cast_cast_fu_180_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_57_fu_166_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_56_fu_158_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_assign_2_fu_188_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_93_cast_fu_194_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_67_fu_102_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_52_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_69_fu_202_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_68_fu_152_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp2_fu_214_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp1_fu_208_p2 : STD_LOGIC_VECTOR (7 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= (tmp2_fu_214_p2 xor tmp1_fu_208_p2);
    tmp1_fu_208_p2 <= (tmp_s_fu_52_p2 xor tmp_67_fu_102_p2);
    tmp2_fu_214_p2 <= (tmp_69_fu_202_p2 xor tmp_68_fu_152_p2);
    tmp_2_i4_cast_cast_fu_130_p3 <= 
        ap_const_lv8_1B when (tmp_55_fu_122_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_2_i9_cast_cast_fu_180_p3 <= 
        ap_const_lv8_1B when (tmp_58_fu_172_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_2_i_cast_cast_fu_80_p3 <= 
        ap_const_lv8_1B when (tmp_52_fu_72_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_50_fu_58_p3 <= y(1 downto 1);
    tmp_51_fu_66_p2 <= std_logic_vector(shift_left(unsigned(x),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_52_fu_72_p3 <= x(7 downto 7);
    tmp_53_fu_108_p3 <= y(2 downto 2);
    tmp_54_fu_116_p2 <= std_logic_vector(shift_left(unsigned(x_assign_fu_88_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_55_fu_122_p3 <= x_assign_fu_88_p2(7 downto 7);
    tmp_56_fu_158_p3 <= y(3 downto 3);
    tmp_57_fu_166_p2 <= std_logic_vector(shift_left(unsigned(x_assign_1_fu_138_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_58_fu_172_p3 <= x_assign_1_fu_138_p2(7 downto 7);
    tmp_67_fu_102_p2 <= (x_assign_fu_88_p2 and tmp_85_cast_fu_94_p3);
    tmp_68_fu_152_p2 <= (x_assign_1_fu_138_p2 and tmp_89_cast_fu_144_p3);
    tmp_69_fu_202_p2 <= (x_assign_2_fu_188_p2 and tmp_93_cast_fu_194_p3);
    tmp_85_cast_fu_94_p3 <= 
        ap_const_lv8_FF when (tmp_50_fu_58_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_89_cast_fu_144_p3 <= 
        ap_const_lv8_FF when (tmp_53_fu_108_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_93_cast_fu_194_p3 <= 
        ap_const_lv8_FF when (tmp_56_fu_158_p3(0) = '1') else 
        ap_const_lv8_0;
    tmp_cast_fu_44_p3 <= 
        ap_const_lv8_FF when (tmp_fu_40_p1(0) = '1') else 
        ap_const_lv8_0;
    tmp_fu_40_p1 <= y(1 - 1 downto 0);
    tmp_s_fu_52_p2 <= (x and tmp_cast_fu_44_p3);
    x_assign_1_fu_138_p2 <= (tmp_54_fu_116_p2 xor tmp_2_i4_cast_cast_fu_130_p3);
    x_assign_2_fu_188_p2 <= (tmp_57_fu_166_p2 xor tmp_2_i9_cast_cast_fu_180_p3);
    x_assign_fu_88_p2 <= (tmp_51_fu_66_p2 xor tmp_2_i_cast_cast_fu_80_p3);
end behav;
